services:
  - type: web
    name: ren-gateway
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: ADMIN_PASSWORD
        value: admin
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite+aiosqlite:///./ren.db   # برای استفاده از SQLite در Render (مسیر نسبی)
      - key: CUSTOM_DOMAIN
        value: ""                             # در صورت نیاز دامنه اختصاصی خود را وارد کنید
      - key: PORT
        value: 8000
